# Generated by Django 3.1.3 on 2020-11-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={},
        ),
    ]
