# Generated by Django 3.1.3 on 2020-11-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201106_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'managed': False},
        ),
    ]
