# Generated by Django 3.1.3 on 2020-11-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201106_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInfo',
            fields=[
                ('ts_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trade_date', models.CharField(max_length=20)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('pre_close', models.FloatField(blank=True, null=True)),
                ('change_price', models.FloatField(blank=True, null=True)),
                ('percent_change', models.FloatField(blank=True, null=True)),
                ('volumn', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_info',
                'managed': False,
            },
        ),
    ]
